version: 2.1

jobs:
  build:
    environment:
      image_user: hyperknot
      image_repo: baseimage16

    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - setup_remote_docker:
          version: default


      - run: python -V; pip -V
      - run: pip install docker~=7.1.0 docker-squash~=1.2.0 --disable-pip-version-check
      - run:
          command: docker build --shm-size 512M -t $image_user/$image_repo:build_cache .
          working_directory: image

      - run: docker-squash -t $image_user/$image_repo:$CIRCLE_TAG $image_user/$image_repo:build_cache

      - run: docker images

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $image_user/$image_repo:$CIRCLE_TAG


workflows:
  version: 2
  tagged_build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
